### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by robwilkerson** [lmars/packer-post-processor-vagrant-s3#10]
So this isn't my first rodeo with Packer or the Vagrant S3 post-processor, but I just started getting the following error when trying to build a box that I've built before:

    fork/exec /usr/local/bin/packer-post-processor-vagrant-s3: no such file or directory

It's true that `/usr/local/bin/packer-post-processor-vagrant-s3` doesn't exist, but I'm not sure why it's expecting it to exist. That seems to be new.

I did update Packer today to 0.7.5 via Homebrew so that could very well have changed everything. Even worse, I have no idea what version I was running before. Any idea what I can do to get past this?

**Comment by robwilkerson** [comment]
For whatever it's worth, I symlinked the executable just to get things going:

    $ ln -s ~/.packer.d/plugins/packer-post-processor-vagrant-s3 /usr/local/bin/packer-post-processor-vagrant-s3

**Comment by lmars** [comment]
@robwilkerson not really sure, but this seems like a packer issue, rather than an issue with this plugin?

**Comment by robwilkerson** [comment]
@lmars It very well could be. I dropped this here since it specifically referenced this post-processor. I didn't see any hard coded reference to the directory in the code, but that doesn't necessarily mean much. :-)

**Comment by bstock92** [comment]
For what it's worth (old issue, still the #1 result for this error message on Google) I observed this error when a packer plugin bundle didn't have the execute permission.
