### ISSUE TITLE
Using AWS-profile for authentication

### ISSUE THREAD

**Issue by michielrensen** [lmars/packer-post-processor-vagrant-s3#14]
Would it be possible to select a AWS profile for authentication to work with role-switching?

**Comment by lmars** [comment]
@michielrensen auth is configured using [aws.GetAuth](https://github.com/lmars/packer-post-processor-vagrant-s3/blob/master/post-processor.go#L79-L82), which [will use the instance role if the credentials are blank](https://github.com/mitchellh/goamz/blob/master/aws/aws.go#L311-L344).
