### ISSUE TITLE
Packer validate doesn't recognize the 'access_key' property

### ISSUE THREAD

**Issue by evarga** [lmars/packer-post-processor-vagrant-s3#15]
The command `packer validate <template file>` returns the following error:

```* unknown configuration key: "access_key"```

All other fields are properly recognized, though.

P.S. The 'build' command also reports the same problem.

**FIX**: the problem is in the documentation. By looking into the source code I have found that the correct name is `access_key_id`. So, instead of `access_key` the documentation should refer to `access_key_id`.

**Comment by lmars** [comment]
@evarga I'll happily accept a PR to change the documentation :smile:

**Comment by lmars** [comment]
Fixed in #17.
