### ISSUE TITLE
Multiple boxes overwrite the manifest file

### ISSUE THREAD

**Issue by conord33** [lmars/packer-post-processor-vagrant-s3#18]
When the post processor is used on a build that has multiple providers the manifest will usually only contain a reference to the provider that finishes last. This seems like it is due a race condition. The post processor only checks the manifest file prior to uploading the box file. If another provider reads the manifest file before the first provider finishes its upload, the second provider will update the manifest without the first providers info. The boxes will upload successfully the only problem is with the manifest file.

There needs to be some kind of second check before uploading the manifest.

**Comment by Jalle19** [comment]
Just hit this problem myself (building with both `virtualbox-iso` and `vmware-iso`). Do you know of any workarounds?
