### ISSUE TITLE
Use aws-sdk-go instead of goamz/s3

### ISSUE THREAD

**Issue by Jalle19** [lmars/packer-post-processor-vagrant-s3#25]
goamz/s3 seems to be deprecated and currently doesn't support some S3 regions at all (e.g. eu-central-1). Currently if you try to set region to eu-central-1 you get this error:

```
* Post-processor failed: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256
```

References:
https://github.com/mitchellh/goamz/issues/166
https://github.com/mitchellh/goamz/pull/230

**Comment by Jalle19** [comment]
Or possibly switch to the upstream library https://github.com/go-amz/amz/tree/v3, it seems like it's still being maintained.

**Comment by lmars** [comment]
@Jalle19 I think we should switch this to aws-sdk-go.

I don't currently have the capacity to make that change, would you be interested in taking it on? I can give you some pointers if necessary.

**Comment by Jalle19** [comment]
I can't promise anything, I was thinking of looking into automatic versioning though.

I've been using this to create a few Vagrant boxes and once I've made some more I was thinking of making a static site generator that shows the available boxes, sample Vagrantfiles etc. (pretty much like Atlas does it).

**Comment by Jalle19** [comment]
For the record I know jack shit about Go so things may take a while.

**Comment by Jalle19** [comment]
I'm testing my way forward with aws-sdk-go, with a bit of luck I hope to have something ready sometime next week.

**Comment by Jalle19** [comment]
@lmars https://github.com/Jalle19/vagrant-registry-generator here's that static site generator I talked about, I'll add some instructions on how to hook it up as a post-processor in Packer shortly. Would be nice if you could try it out and give me some feedback on if there's anything missing.
