### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by lmars** [lmars/packer-post-processor-vagrant-s3#34]
@Jalle19 would you be interested in becoming a maintainer for this project?

**Comment by Jalle19** [comment]
@lmars sure

**Comment by lmars** [comment]
@Jalle19 ok great, I have given you push access and also created a MAINTAINERS file, do you want to add yourself to that file and push it?

**Comment by Jalle19** [comment]
Sure, thanks!

**Comment by Jalle19** [comment]
Closing this one, thanks for the vote of confidence!
