### ISSUE TITLE
Support Reduced Redundancy?

### ISSUE THREAD

**Issue by mikemcrill** [lmars/packer-post-processor-vagrant-s3#36]
Would be nice if there was an option to specify the storage class for this, such as Reduced Redundancy.

**Comment by Jalle19** [comment]
Sounds like a good idea, I didn't even know this stuff existed before now.

**Comment by lmars** [comment]
@mikemcrill are you interested in contributing this enhancement?

**Comment by mikemcrill** [comment]
Sure, I'll work on a PR for you next week.

**Comment by lmars** [comment]
Great! Let us know if you need any pointers.

**Comment by mikemcrill** [comment]
Sorry for not updating this, I have not been able to work on this at all and I don't think I will have any time in the near future.

**Comment by Jalle19** [comment]
I'll take a stab at this, it looks very simple to implement.
