### ISSUE TITLE
Adding a CHANGELOG and tag releases

### ISSUE THREAD

**Issue by Jalle19** [lmars/packer-post-processor-vagrant-s3#46]
@lmars since this project has seen more activity lately I figured it would be a good idea to add a CHANGELOG.md file and tag some previous releases retroactively? We could say that `1.0.0` was e.g. around the time when we switched to the official AWS Go SDK, then just add minor releases after that whenever one or more PRs were merged.

**Comment by lmars** [comment]
Yep sounds good to me.
