### ISSUE TITLE
Error during multipart upload

### ISSUE THREAD

**Issue by Danita** [lmars/packer-post-processor-vagrant-s3#52]
Hi! First of all thanks for this plugin! 😄 

I'm getting the following error while trying to upload a small-ish (400MB) box:

```
==> virtualbox-iso: Running post-processor: vagrant-s3
==> virtualbox-iso (vagrant-s3): Preparing to upload box for 'virtualbox' provider to S3 bucket 'vagrant-my'
    virtualbox-iso (vagrant-s3): Box to upload: packer_virtualbox-iso_virtualbox.box (454715755 bytes)
    virtualbox-iso (vagrant-s3): Using 1.0.4 as new version
    virtualbox-iso (vagrant-s3): Generating checksum
    virtualbox-iso (vagrant-s3): Checksum is 466d2575dbc8f86067f758e868d0590d2ce3cc76aa3b73d2b274b8011c9fc18b
    virtualbox-iso (vagrant-s3): Uploading box to S3: vagrant/boxes/mycompanyname/myproject/1.0.4/packer_virtualbox-iso_virtualbox.box
Build 'virtualbox-iso' errored: 1 error(s) occurred:

* Post-processor failed: MultipartUpload: upload multipart failed 
upload id: VzSSAb5gqC6vWaGN2qqWfZonVFALk3MPxtjOFzIihoqOZ6ov_wL08WKF5ASdcBEt5BtksW.hJ2d98OGBCklYT2XO0Cbj6vzfk7_wtF.W9hA8LQXu16IrQ8Ji0Xfc8Aly
caused by: RequestError: send request failed
caused by: Put https://vagrant-my.s3-us-west-2.amazonaws.com/vagrant/boxes/mycompanyname/myproject/1.0.4/packer_virtualbox-iso_virtualbox.box?partNumber=7&uploadId=VzSSAb5gqC6vWaGN2qqWfZonVFALk3MPxtjOFzIihoqOZ6ov_wL08WKF5ASdcBEt5BtksW.hJ2d98OGBCklYT2XO0Cbj6vzfk7_wtF.W9hA8LQXu16IrQ8Ji0Xfc8Aly: dial tcp: lookup vagrant-my.s3-us-west-2.amazonaws.com on 127.0.1.1:53: dial udp 127.0.1.1:53: i/o timeout
```

Judging by the `partNumber=7` it seems that it successfully uploaded 6 parts of 7 estimated (400/64) and it failed by timeout. But I cannot figure timeout of what. My connection is slow, but could be that causing trouble?

Thanks!!

**Comment by Jalle19** [comment]
It looks like a timeout when the DNS lookup for `vagrant-my.s3-us-west-2.amazonaws.com` is made. Do you have any way to test this on a faster/more stable connection?

**Comment by Danita** [comment]
@Jalle19 Thanks for your reply. Sadly we cannot test it with a better connection right now, but we made the following changes to `post-processor.go` and it's working now:

```diff
diff --git a/post-processor.go b/post-processor.go
index ca05887..f247f4a 100644
--- a/post-processor.go
+++ b/post-processor.go
@@ -269,7 +269,8 @@ func (p *PostProcessor) uploadBox(box, boxPath string) error {
 
        // upload the file
        uploader := s3manager.NewUploader(p.session, func(u *s3manager.Uploader) {
-               u.PartSize = 1024 * 1024 * 64
+               u.PartSize = 1024 * 1024 * 5
+               u.Concurrency = 1
        })
 
        _, err = uploader.Upload(&s3manager.UploadInput{
```

Maybe making those changes parametrizable so people with poor connections can still use the plugin?

**Comment by Jalle19** [comment]
Do you know if it was the lowered `PartSize` or `Concurrency` that actually helped, or both? I think the part size can be lowered for everyone without having an adverse effect on fast connections, but setting `Concurrency` to `1` sounds like it will make things slower in general.

**Comment by gdbonino** [comment]
Hi, I'm working with @danita on this. After several tests we determined our problem seems to be with concurrency. Using `PartSize = 64` and `Concurrency = 1`, our 800MB box uploaded without problems. 
 
We made a fork at https://github.com/gdbonino/packer-post-processor-vagrant-s3/commits/master where you can set both config via params, so people like us with less stable connections have a chance to use the plugin. We can submit a pull request if you want. 
 
Example usage: 

            {
                "type": "vagrant-s3",
                "region": "us-west-2",
                "bucket": "my-s3-bucket",
                "manifest": "vagrant/json/{{ user `box_organization` }}/{{ user `box_name` }}.json",
                "box_dir": "vagrant/boxes/{{ user `box_organization` }}/{{ user `box_name` }}",
                "box_name": "{{ user `box_organization` }}/{{ user `box_name` }}",
                "version": "{{ user `version` }}",
                "concurrency": 1
            }
